include:
  - Config/templates.yml

name: Fueling

attributes:
  ORGANIZATIONNAME: "snafu"

options:
  bundleIdPrefix: org.snafu
  deploymentTarget:
    iOS: 17.0
    watchOS: 10.0

settings:
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS : YES
  DEVELOPMENT_TEAM : A3UXBEBE8Z
  LOCALIZATION_PREFERS_STRING_CATALOGS : YES
  ENABLE_USER_SCRIPT_SANDBOXING : NO
  DEAD_CODE_STRIPPING : YES
  SWIFT_STRICT_CONCURRENCY : complete
  SWIFT_VERSION : 6.1

schemes:
  Fueling:
    templates:
      - App
  WatchFueling Watch App:
    templates:
      - WatchApp

targets:
  Fueling:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - Shared
      - Fueling
    dependencies:
      - target: "WatchFueling Watch App"
    info:
      path: Fueling/Gen/Info.plist
      properties:
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest: 
          UIApplicationSupportsMultipleScenes: YES
          UISceneConfigurations: []
        UILaunchScreen:
          UILauchScreen: []
        UIBackgroundModes:
          - remote-notification
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: Fueling/Gen/Fueling.entitlements
    postBuildScripts:
      - path: Config/buildversion
        name: Build Version
        showEnvVars: NO
        basedOnDependencyAnalysis: NO
      - path: Config/swiftlint
        name: Swift Lint
        showEnvVars: NO
        basedOnDependencyAnalysis: NO
  WatchFueling Watch App:
    type: application
    platform: watchOS
    deploymentTarget: 10.0
    sources:
      - Shared
      - WatchFueling Watch App
    # info:
    #   path: WatchFueling/Gen/Info.plist
    #   properties:
    #     UISupportedInterfaceOrientations:
    #       - UIInterfaceOrientationPortrait
    #       - UIInterfaceOrientationPortraitUpsideDown
    # entitlements:
    #   path: Fueling/Gen/Fueling.entitlements
    postBuildScripts:
      # - path: Config/buildversion
      #   name: Build Version
      #   showEnvVars: NO
      #   basedOnDependencyAnalysis: NO
      - path: Config/swiftlint
        name: Swift Lint
        showEnvVars: NO
        basedOnDependencyAnalysis: NO
