name: Fueling

options:
  groupOrdering:
    - order: [FuelingStore, Fueling, Fueling Watch App, Packages, Products]

settings:
  base:
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    CODE_SIGN_IDENTITY: Apple Development
    CODE_SIGN_STYLE: Automatic
    DEAD_CODE_STRIPPING: YES
    DEVELOPMENT_TEAM: A3UXBEBE8Z
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    LOCALIZATION_PREFERS_STRING_CATALOGS: YES
    PRODUCT_NAME: $(TARGET_NAME)
    SWIFT_EMIT_LOC_STRINGS: YES
    SWIFT_STRICT_CONCURRENCY: YES
    SWIFT_VERSION: 6.1
    # the following are replaced in the target Info.plists by a post
    # build script. They are needed (?) to build the plist that the
    # script then modifies.
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
  configs:
    debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
    release:
      VALIDATE_PRODUCT:  YES

targets:
  Fueling:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - Shared
      - Fueling
      - FuelingStore
    dependencies:
      - target: "Fueling Watch App"
      - package: UDF
    settings:
      base:
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: $(TARGET_NAME)
        INFOPLIST_KEY_NSHumanReadableCopyright: Copyright 2025 Marco S Hyman
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        PRODUCT_BUNDLE_IDENTIFIER: org.snafu.Fueling
    postBuildScripts:
      - path: .buildversion.sh
        name: Build Version
        showEnvVars: NO
        basedOnDependencyAnalysis: NO
      - path: .swiftlint.sh
        name: Swift Lint
        showEnvVars: NO
        basedOnDependencyAnalysis: NO

  FuelingTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 17.0
    dependencies:
      - target: Fueling
    sources:
      - FuelingTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_NAME: $(TARGET_NAME)
      PRODUCT_BUNDLE_IDENTIFIER: org.snafu.FuelingTests
    schemes: none
 
  Fueling Watch App:
    type: application
    platform: watchOS
    deploymentTarget: 10.0
    dependencies:
      - package: UDF
    sources:
      - Shared
      - Fueling Watch App
    settings:
      base:
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: $(PROJECT_NAME)
        INFOPLIST_KEY_UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: org.snafu.$(PROJECT_NAME)
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
        PRODUCT_BUNDLE_IDENTIFIER: org.snafu.Fueling.watchkitapp
    postBuildScripts:
      - path: .swiftlint.sh
        name: Swift Lint
        showEnvVars: NO
        basedOnDependencyAnalysis: NO

  FuelingWatchTests:
    type: bundle.unit-test
    platform: watchOS
    deploymentTarget: 10.0
    dependencies:
      - target: Fueling Watch App
      - package: UDF
    sources:
      - FuelingWatchTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_NAME: $(TARGET_NAME)
      PRODUCT_BUNDLE_IDENTIFIER: org.snafu.FuelingWatchTests
    schemes: none

packages:
  UDF:
    path: UDF

schemes:
  Fueling:
    build:
      targets:
        Fueling: all
    run:
      config: Debug
      # environmentVariables:
      #   VARIABLE: VALUE
    test:
      config: Debug
      gatherCoverageData: YES
      targets:
        - name: FuelingTests
      # targets:
      #   - name: Fueling
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: YES

  Fueling Watch App:
    build:
      targets:
        Fueling Watch App: all
    run:
      config: Debug
      # environmentVariables:
      #   VARIABLE: VALUE
    test:
      config: Debug
      commandLineArguments:
        "-TESTING": true
      gatherCoverageData: YES
      targets:
        - name: FuelingWatchTests
